### ISSUE TITLE
Angular 19 ZoneAwarePromise error

### ISSUE THREAD

**Issue by iDoes26** [FriendlyCaptcha/friendly-captcha-sdk#24]
I have successfully used friendlyCaptcha v1 (friendly-challenge package), when trying to upgrade to v2 using the upgrade guide (https://developer.friendlycaptcha.com/docs/v2/guides/upgrading-from-v1/javascript-api) I am getting the following error:

```
main.ts:5 ERROR TypeError: Class constructor ZoneAwarePromise cannot be invoked without 'new'
    at new fcPatch (sdk.js:835:70)
    at ZoneAwarePromise.then (zone.js:2727:38)
    at _ApplicationInitStatus.runInitializers (core.mjs:22356:36)
    at core.mjs:34729:18
    at _callAndReportToErrorHandler (core.mjs:22488:20)
    at core.mjs:34727:12
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:6495:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
```

I am using Angular 19.

**Comment by gzuidhof** [comment]
This should be fixed with the release of `0.1.12` - do write here in case you are still seeing issues and I will reopen this ticket.

**Comment by iDoes26** [comment]
Now I am seeing these two identical errors:

```
main.ts:5 ERROR TypeError: Promise.all(...).then(...).catch is not a function
    at _ApplicationInitStatus.runInitializers (core.mjs:22358:8)
    at core.mjs:34729:18
    at _callAndReportToErrorHandler (core.mjs:22488:20)
    at core.mjs:34727:12
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:6495:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
    at _NgZone.run (core.mjs:6347:24)
    at bootstrap (core.mjs:34683:17)
    
main.ts:6 TypeError: Promise.all(...).then(...).catch is not a function
    at _ApplicationInitStatus.runInitializers (core.mjs:22358:8)
    at core.mjs:34729:18
    at _callAndReportToErrorHandler (core.mjs:22488:20)
    at core.mjs:34727:12
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:6495:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
    at _NgZone.run (core.mjs:6347:24)
    at bootstrap (core.mjs:34683:17)
```

**Comment by gzuidhof** [comment]
Hmm, is it maybe possible to change the import order and see if that changes anything? In this stack trace there is no `fcPatch` 🤔 

From what I understand the `ZoneAwarePromise` comes from [`zone.js`](https://www.npmjs.com/package/zone.js) inside of Angular. I attempted to reproduce the issue in [this test case](https://github.com/FriendlyCaptcha/friendly-captcha-sdk/blob/main/sdktest/test/zone/main.tmpl.ts#L9). Do you maybe have a minimal example to reproduce so that we can put that in a test case and fix it?

Thank you for the help so far :)

**Comment by gzuidhof** [comment]
Thank you so much! That was really helpful in iterating on a solution.

In the end I think it's best if we remove the patch entirely to prevent issues, I created a PR with some thoughts in #26.

A small tip on your implementation: you currently create the SDK within a component - that may create issues if you have more than one widget on a page.

It's best to create it as a singleton, something like this can work (or maybe Angular provides a better way with a `Provider` of some sort, I'm hardly an Angular expert):


```javascript
const sdk = window.FriendlyCaptchaSDK || new FriendlyCaptchaSDK( /* options */);
window.FriendlyCaptchaSDK = sdk;
```

**Comment by iDoes26** [comment]
0.1.14 works! Thanks :)
